version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
    ports:
      - 3000:3000
    environment:
      - DB_CONNECT=mongodb://mongo:27017/mydatabase
      - TOKEN_SECRET=hello
      - EXPIRE_TIME=3600000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017

volumes:
  node_modules:
  dist:
